#!/bin/bash
sudo apt install hping3
# equired essentials for Hydra
sudo apt-get -y install build-essential
sudo apt-get install git
sudo apt-get install hydra
sudo apt-get install python3
pip install --pre scapy[basic]
sudo python3 main.py